### ISSUE TITLE
build failures (trunk)

### ISSUE THREAD

**Issue by thorkill** [thorkill/eresi-tickets3#135]
At least libstderesi is missing -ldl:

../libstderesi//libstderesi32.a(std-types.32.o): In function `revm_vector_entry_display':
/home/glenn/eresi/libstderesi/type/vectors.c:156: undefined reference to `dladdr'

Also, the compiler switch -Wextra is used by libgdbwrap, which isn't supported by my compiler (3.3, used for compatibility with my development environment).  For compatibility, use "-W", which is still supported.

----
Reported by: Thu Feb 18 09:41:20 2010 on glenn

**Comment by thorkill** [comment]
[thorkill] hey,

could you post some informations about your os and compiler version?

**Comment by thorkill** [comment]
[glenn] gcc 3.3 in Linux, out of r1402.  I havn't tested with a newer compiler, but -W is equivalent to -Wextra and works on both new and old compilers (according to http://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html).

About -ldl, I figured out what's going on: it's because I'm linking statically (to have a simpler local environment), and the error is when linking elfsh32 (not libstderesi itself), since it needs -ldl explicitly.

**Comment by thorkill** [comment]
[thorkill] Static should work now, I'm not sure if we want to support gcc 3.3.x, I don't have any - you could modify the configure script on your own and patch it for us. Make sure it works with gcc >3.3 .
